version: '3.8'

services:
  front:
    build:
      context: ./../frontend
      args:
        REACT_APP_API: http://127.0.0.1:${BACK_PORT:-9000}
    ports:
      - ${FRONT_PORT:-3000}:80

  back:
    build:
      context: ./../backend
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 9000
      MONGO_URL: mongodb://${DB_USER:-root}:${DB_PASS:-toor}@mongo:27017
      JWT_SECRET: ${JWT_SECRET:-mveu}
      JWT_EXPIRES: ${JWT_EXPIRES:-24h}
    ports:
      - ${BACK_PORT:-9000}:9000

  mongo:
    image: mongo:4.4.27
    restart: always
    environment:
      #MONGO_INITDB_DATABASE: mveu
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-toor}
    volumes:
      - ./data:/data/db
  
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    profiles:
      - mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS:-toor}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER:-root}:${DB_PASS:-toor}@mongo:27017
    ports:
      - ${MONGO_EXPRESS_PORT:-9001}:8081
